name: Run Databricks using RESTAPI

on:
  push:
    branches:
      - main

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    env:
            DATABRICKS_HOST: 'https://adb-3280056724355955.15.azuredatabricks.net/'
            DATABRICKS_TOKEN: 'dapi77e90e5f962ab1333f97738b55568d2e-3'
            NOTEBOOK_PATH: '/Workspace/demo/test'
            EXISTING_CLUSTER_ID: '1030-230645-6lgp1r1a'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Databricks Notebook
      id: run-notebook
      run: |
        DATABRICKS_HOST=${{ env.DATABRICKS_HOST }}
        DATABRICKS_TOKEN=${{ env.DATABRICKS_TOKEN }}
        NOTEBOOK_PATH=${{ env.NOTEBOOK_PATH }}
        EXISTING_CLUSTER_ID=${{ env.EXISTING_CLUSTER_ID }}
        JOB_ID=$(curl -X POST -H "Authorization: Bearer $DATABRICKS_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{
                \"run_name\": \"GitHub Actions Run\",
                \"existing_cluster_id\": \"$EXISTING_CLUSTER_ID\",
                \"notebook_task\": {
                  \"notebook_path\": \"$NOTEBOOK_PATH\"
                }
              }" \
          $DATABRICKS_HOST/api/2.0/jobs/runs/submit | jq -r '.run_id')

        echo "Notebook run ID: $JOB_ID"

        # Check the status of the notebook run
        STATUS="PENDING"
        while [[ "$STATUS" == "PENDING" || "$STATUS" == "RUNNING" ]]; do
          STATUS=$(curl -X GET -H "Authorization: Bearer $DATABRICKS_TOKEN" \
            $DATABRICKS_HOST/api/2.0/jobs/runs/get?run_id=$JOB_ID | jq -r '.state.life_cycle_state')
          echo "Current status: $STATUS"
          sleep 30
        done

        if [[ "$STATUS" != "TERMINATED" ]]; then
          echo "Notebook run failed with status: $STATUS"
          exit 1
        fi

        echo "Notebook run completed successfully"
