name: Run Databricks Notebook

on:
    push:
        branches:
            - main
jobs:
    run-notebook:
        runs-on: ubuntu-latest
        env:
            DATABRICKS_HOST: 'https://adb-3280056724355955.15.azuredatabricks.net/'
            DATABRICKS_TOKEN: 'dapi77e90e5f962ab1333f97738b55568d2e-3'
            NOTEBOOK_PATH: '/Workspace/demo/test'
            EXISTING_CLUSTER_ID: '1030-230645-6lgp1r1a'
        steps:
            - uses: actions/checkout@v2

            - name: Run Databricks Notebook
              id: run-notebook
              uses: databricks/run-notebook@v0.0.3
              with:
                databricks-host: ${{ env.DATABRICKS_HOST }}
                databricks-token: ${{ env.DATABRICKS_TOKEN }}
                workspace-notebook-path: ${{ env.NOTEBOOK_PATH }}
                existing-cluster-id: ${{ env.EXISTING_CLUSTER_ID }}

            - name: Get Notebook Output
              run: |
                echo "Notebook output: ${{ steps.run-notebook.outputs.notebook-output }}"

            - name: Save Notebook Output
              run: |
                echo "${{ steps['run-notebook'].outputs['notebook-output'] }}" > notebook_output.json

            - name: Read and Print Notebook Output
              run: |
                cat notebook_output.json

            - name: check Notebook Output
              run: |
                status=$(jq -r '.test_summary_status // empty' notebook_output.json)
                echo "Notebook run status: $status"

                if [[ "$status" != "SUCCESS" ]]; then
                echo "Notebook run failed with status: $status"
                exit 1
                fi

                echo "Notebook run completed successfully"
